<?php
// +----------------------------------------------------------------------
// | Ht.Memorial
// +----------------------------------------------------------------------
// | Copyright (c) 2017-2017 http://www.yn123.com All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: ding <dingzhangze@163.com>
// +----------------------------------------------------------------------

namespace app\business\controller;

use think\Db;
use app\business\service\DataService;
use app\business\service\ToolsService;


/**
 * 预约信息管理
 * Class Bespeak
 * @package app\admin\controller
 * @author ding <dingzhangze@163.com>
 * @date 2017/08/09
 */
class Bespeak extends BasicBusiness
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->user = session('b_user');
        $this->uid = $this->user['create_by'];
    }
    /**
     * 指定当前数据表
     * @var string
     */
    protected $table = 'cemetery_bespeak';
    /**
     * 安葬列表
     */
    public function index()
    {
        $this->title = '预约信息管理';

        // 获取到所有GET参数
        $get = $this->request->get();

        $db = Db::name($this->table)->where('create_by',$this->uid);
        // 应用搜索条件
        foreach (['customer', 'phone'] as $key) {
            if (isset($get[$key]) && $get[$key] !== '') {
                $db->where($key, 'like', "%{$get[$key]}%");
            }
        }
        // 实例化并显示
        parent::_list($db, false);
    }

    /*
    * 添加客户回访
    */
    public function addvisit()
    {
        return $this->_form($this->table, 'addvisit');
    }

    protected function _addvisit_form_filter(&$vo)
    {
        if ($this->request->isPost()) {
            $vo['status']=1;
            $res=Db::name($this->table)->update($vo);
            $res !== false ? $this->success('恭喜，保存成功哦！', url('/').'business.html#'.url('bespeak/index').'?spm='.$this->spm) : $this->error('保存失败，请稍候再试！');
        }
    }

    /**
     * 删除预约信息
     */
    public function del() {
        if (DataService::update($this->table)) {
            $this->success("删除成功！", '');
        }
        $this->error("删除失败，请稍候再试！");
    }

    /*
     * 客户回访
     */
    public function cvisit()
    {
        // 设置页面标题
        $this->title = '客户回访';
        // 获取到所有GET参数
        $get = $this->request->get();
        $map=[
            'id'=>$get['id']
        ];
        // 实例Query对象
        $db = Db::name($this->table)->where($map);
        parent::_list($db);
    }

    /**
     * 删除回访记录
     */
    public function delvisit() {
        if (DataService::update($this->tableVisit)) {
            $this->success("删除成功！", '');
        }
        $this->error("删除失败，请稍候再试！");
    }
}





