<?php
// +----------------------------------------------------------------------
// | Ht.Memorial
// +----------------------------------------------------------------------
// | Copyright (c) 2017-2017 http://www.yn123.com All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: ding <dingzhangze@163.com>
// +----------------------------------------------------------------------

namespace app\business\controller;

use app\business\service\DataService;
use app\business\service\ToolsService;
use think\Db;

/**
 * 套餐管理
 * Class Combo
 * @package app\business\controller
 * @author ding <dingzhangze@163.com>
 * @date 2017/8/10
 */
class Combo extends BasicBusiness
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->user = session('b_user');
        $this->uid = $this->user['create_by'];
    }

    /**
     * 指定当前数据表
     * @var string
     */
    protected $table = 'cemetery_combo';


    /**
     * 套餐列表
     */
    public function Package()
    {
        $get = $this->request->get();

        if($get['type']==0){
            $this->title = '碑文套餐列表';
        }elseif ($get['type']==1){
            $this->title = '安葬套餐列表';
        }else{
            $this->title = '寄存套餐列表';
        }
        // 实例Query对象
        $db = Db::name($this->table)->where(['type'=>$get['type'],'create_by'=>$this->uid]);
        // 应用搜索条件
        foreach (['name', 'desc'] as $key) {
            if (isset($get[$key]) && $get[$key] !== '') {
                $db->where($key, 'like', "%{$get[$key]}%");
            }
        }

        parent::_list($db);
    }


//    /**
//     * 分类 列表数据处理
//     * @param array $data
//     */
//    protected function _Package_data_filter(&$data)
//    {
//
//        foreach ($data as &$vo) {
//            $vo['ids'] = join(',', ToolsService::getArrSubIds($data, $vo['id']));
//            $exist = Db::name($this->table)->where('pid', $vo['id'])->count();
//
//
//            if($exist) {
//                $vo['has_child'] = true;
//            }else {
//                $vo['has_child'] = false;
//            }
//        }
//
//        $data = ToolsService::arr2table($data);
//    }


    /**
     * 添加套餐
     */
    public function addPackage()
    {
        $result = $this->_form($this->table);

        if(isset($result['id'])){
            $this->title = '编辑套餐';
        }else {
            $this->title = '添加套餐';
        }

        return $this->_form($this->table, 'packageform', null, []);

    }
    /**
     * 添加套餐 返回结果跳转处理
     * @param $result
     */
    protected function _addPackage_form_result(&$result)
    {
        $result !== false ? $this->success('恭喜，保存成功哦！', url('/').'business.html#'.url('package').'?type='.$this->request->get('type').'&spm='.$this->spm) : $this->error('保存失败，请稍候再试！');
    }

    /**
     * 编辑套餐
     */
    public function editPackage()
    {
        return $this->addPackage();
    }

//    /**
//     * 添加套餐内容
//     */
//    public function addcombo()
//    {
//        // 获取主套餐
//        $pid = $this->request->get('pid');
//        $menus = Db::name($this->table)->where('id',$pid)->find();
//        $this->assign('menus', $menus);
//        return $this->_form($this->table, 'detailform');
//
//    }

    /**
     * 删除
     */
    public function delpackage() {
        if (DataService::update($this->table)) {
            $this->success("删除成功！", '');
        }
        $this->error("删除失败，请稍候再试！");
    }

}