<?php
// +----------------------------------------------------------------------
// | Ht.Memorial
// +----------------------------------------------------------------------
// | Copyright (c) 2017-2017 http://www.yn123.com All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: ding <dingzhangze@163.com>
// +----------------------------------------------------------------------

namespace app\business\controller;

use app\admin\service\DataService;
use app\admin\service\ToolsService;
use think\Db;

/**
 * 合同管理管理
 * Class Contract
 * @package app\business\controller
 * @author ding <dingzhangze@163.com>
 * @date 2017/7/25
 */
class Contract extends BasicBusiness
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->user = session('b_user');
        $this->uid = $this->user['create_by'];
    }
    /**
     * 指定当前数据表
     * @var string
     */
    protected $table = 'Cemetery_contract';
    /*
     * 文章列表管理
     */
    public function index()
    {
        $this->title='合同模板管理';
        $Map=[
            'create_by'=>$this->uid
        ];
        $db = Db::name($this->table)->where($Map)->order('id asc');
        parent::_list($db, false);
    }

    /**
     * 添加文章
     */
    public function add()
    {
        $this->title='添加文章';
        return $this->_form($this->table,'form');
    }

    protected function _form_result(&$result)
    {
        $result !== false ? $this->success('恭喜，保存成功哦！', url('/').'business.html#'.url('index').'?spm='.$this->spm) : $this->error('保存失败，请稍候再试！');
    }

    /**
     * 编辑文章
     */
    public function edit()
    {
        $this->title='编辑文章';
        return $this->add();
    }

    /**
     * 删除文章
     */
    public function del()
    {
        if (DataService::update($this->table)) {
            $this->success("删除成功！", '');
        }
        $this->error("删除失败，请稍候再试！");
    }

    /**
     * 文章待审核状态
     */
    public function forbid()
    {
        if (DataService::update($this->table)) {
            $this->success("待审核状态添加成功！", '');
        }
        $this->error("待审核失败，请稍候再试！");
    }

    /**
     * 文章审核
     */
    public function resume()
    {
        if (DataService::update($this->table)) {
            $this->success("审核成功！", '');
        }
        $this->error("审核失败，请稍候再试！");
    }

}