<?php
// +----------------------------------------------------------------------
// | Ht.Memorial
// +----------------------------------------------------------------------
// | Copyright (c) 2017-2017 http://www.yn123.com All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: ding <dingzhangze@163.com>
// +----------------------------------------------------------------------

namespace app\business\controller;

use think\Db;
use app\business\service\DataService;
use app\business\service\ToolsService;


/**
 * 陵园设置
 * Class Cemetery
 * @package app\admin\controller
 * @author ding <dingzhangze@163.com>
 * @date 2017/06/27
 */
class Grave extends BasicBusiness
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->user = session('b_user');
        $this->uid=$this->user['create_by'];

        $grave=Db::name($this->table)->where(['pid'=>0, 'is_deleted'=>0, 'create_by'=>$this->uid])->find();
        $this->assign('grave',$grave);
    }

    /**
     * 指定当前数据表
     * @var string
     */
    protected $table = 'CemeteryTomb';


    /**
     * 陵园管理
     */
    public function index()
    {
        // 设置页面标题
        $this->title = '陵园管理';
        // 获取到所有GET参数
        $get = $this->request->get();

        // 实例Query对象
        $map=[
            'pid'=>0,
            'is_deleted'=>0,
            'create_by'=>$this->uid
        ];
        $db = Db::name($this->table)->where($map);
        // 应用搜索条件
        foreach (['username', 'phone'] as $key) {
            if (isset($get[$key]) && $get[$key] !== '') {
                $db->where($key, 'like', "%{$get[$key]}%");
            }
        }
        // 实例化并显示
        parent::_list($db);
    }

    /*
    *添加陵园
    */
    public function add()
    {
        return $this->_form($this->table, 'form');
    }

    /**
     * 添加陵园辅助方法
     */

    public function _add_form_filter()
    {
        if ($this->request->isPost()) {
            $result = input('post.');
            $province=$result['grave_province'];
            $city=$result['grave_city'];
            $res=Db::name('cemetery_area')->where('province',$province)->find();
            if(!empty($res)){
                $a_id=$res['id'];
            }else{
                $a_id=Db::name('cemetery_area')->insertGetId(['province'=>$province]);
            }
            $ret=Db::name('cemetery_area')->where('city',$city)->find();
            if(empty($ret)){
               $suc= Db::name('cemetery_area')->insert(['city'=>$city,'pid'=>$a_id]);
            }
            $ss=Db::name($this->table)->insertGetId($result);
            $ss !== false ? $this->success('恭喜，保存成功哦！', url('/') . 'business.html#' . url('grave/index') . '?spm=' . $this->spm) : $this->error('保存失败，请稍候再试！');
        }
    }

    /**
     * 编辑陵园
     */
    public function edit()
    {
        return $this->add();
    }

    /**
     * 删除陵园
     */
    public function del() {
        if (DataService::update($this->table)) {
            $this->success("删除成功！", '');
        }
        $this->error("删除失败，请稍候再试！");
    }
}
