<?php
// +----------------------------------------------------------------------
// | Ht.Memorial
// +----------------------------------------------------------------------
// | Copyright (c) 2017-2017 http://www.yn123.com All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: ding <dingzhangze@163.com>
// +----------------------------------------------------------------------

namespace app\business\controller;

use think\Db;
use app\business\service\DataService;
use app\business\service\ToolsService;
/**
 * 公墓管理
 * Class Cemetery
 * @package app\admin\controller
 * @author ding <dingzhangze@163.com>
 * @date 2017/06/01
 */
class Seller extends BasicBusiness
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->user = session('b_user');
        $this->uid=$this->user['create_by'];
    }

    /**
     * 指定当前数据表
     * @var string
     */
    protected $table = 'BusinessSeller';

    /*
     * 客户列表
     */
    public function index()
    {
        // 设置页面标题
        $this->title = '销售人员管理';
        // 获取到所有GET参数
        $get = $this->request->get();
        // 实例Query对象
        $map=[
            'is_deleted'=>0,
            'create_by'=>$this->uid
        ];
        $db = Db::name($this->table)->where($map);
        // 应用搜索条件
        foreach (['username', 'phone'] as $key) {
            if (isset($get[$key]) && $get[$key] !== '') {
                $db->where($key, 'like', "%{$get[$key]}%");
            }
        }
        // 实例化并显示
        parent::_list($db);
    }

    /*
     * 销售人员添加
     */
    public function add()
    {

        return $this->_form($this->table, 'form');
    }

    protected function _add_form_filter(&$data)
    {

        if ($this->request->isPost()) {

            $data['password'] = admin_md5($this->request->param('password'));

//            if (isset($data['id'])) {
//                unset($data['username']);
//            } elseif (Db::name($this->table)->where('username', $data['username'])->find()) {
//                $this->error('用户账号已经存在，请使用其它账号！');
//            }
        }
    }

    /**
     * 编辑
     */
    public function edit()
    {
        return $this->_form($this->table, 'form');
    }


    /**
     * 删除用户
     */
    public function del() {
        if (DataService::update($this->table)) {
            $this->success("用户删除成功！", '');
        }
        $this->error("用户删除失败，请稍候再试！");
    }

    /**
     * 用户禁用
     */
    public function forbid()
    {
        if (DataService::update($this->table)) {
            $this->success("用户禁用成功！", '');
        }
        $this->error("用户禁用失败，请稍候再试！");
    }

    /**
     * 用户启用
     */
    public function resume()
    {
        if (DataService::update($this->table)) {
            $this->success("用户启用成功！", '');
        }
        $this->error("用户启用失败，请稍候再试！");
    }

    /*
     * 业绩查询
     */
    public function record()
    {
        // 设置页面标题
        $this->title = '销售业绩';
        // 获取到所有GET参数
        $get = $this->request->get();
        $map=[
            'is_deleted'=>0,
            'id'=>$get['id']
        ];
        $sell=Db::name('BusinessSeller')->where($map)->find();
       $maps=[
           'is_deleted'=>0,
           'salesperson'=>$sell['username'],
           'order_state'=>20
       ];
        // 实例Query对象
        $db = Db::name('CemeteryOrder')->where($maps);
        // 应用搜索条件
//        foreach (['username', 'phone'] as $key) {
//            if (isset($get[$key]) && $get[$key] !== '') {
//                $db->where($key, 'like', "%{$get[$key]}%");
//            }
//        }
        // 实例化并显示
        parent::_list($db);
    }

}
