<?php
// +----------------------------------------------------------------------
// | Ht.Memorial
// +----------------------------------------------------------------------
// | Copyright (c) 2017-2017 http://www.yn123.com All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: ding <dingzhangze@163.com>
// +----------------------------------------------------------------------

namespace app\business\controller;

use app\admin\service\DataService;
use app\admin\service\ToolsService;
use think\Db;

/**
 * 陵园轮播管理
 * Class Article
 * @package app\business\controller
 * @author ding <dingzhangze@163.com>
 * @date 2017/7/25
 */
class Slider extends BasicBusiness
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->user = session('b_user');
        $this->uid = $this->user['create_by'];
    }
    /**
     * 轮播图片表
     * @var string
     */
    protected $table = 'grave_slider';

    /**
     * 轮播管理
     */
    public function index()
    {
        $this->title='轮播管理';
        $Map=[
            'create_by'=>$this->uid,
        ];
        $db = Db::name($this->table)->where($Map)->order('id asc');
        parent::_list($db, false);
    }


    /**
     * 获取陵园 辅助方法
     * @return array
     */
    private function _getGrave() {
        $map=[
            'pid'=>0,
            'is_deleted'=>0,
            'create_by'=>$this->uid
        ];
        $_menus = Db::name('CemeteryTomb')->where($map)->order('sort desc,id desc')->select();
        $menus = ToolsService::arr2table($_menus);
        foreach ($menus as $key => &$menu) {
            if (substr_count($menu['path'], '-') > 3) {
                unset($menus[$key]);
                continue;
            }
            if (isset($vo['pid'])) {
                $current_path = "-{$vo['pid']}-{$vo['id']}";
                if ($vo['pid'] !== '' && (stripos("{$menu['path']}-", "{$current_path}-") !== false || $menu['path'] === $current_path)) {
                    unset($menus[$key]);
                }
            }
        }

        return $menus;
    }

    /**
     * 添加轮播
     */
    public function add()
    {
        // 获取陵园
        $menus = $this->_getGrave();
        $this->assign('menus', $menus);
        return $this->_form($this->table,'form');
    }

    /**
     * 编辑轮播
     */
    public function edit()
    {
        return $this->add();
    }

    /**
     * 删除轮播
     */
    public function del() {
        if (DataService::update($this->table)) {
            $this->success("删除成功！", '');
        }
        $this->error("删除失败，请稍候再试！");
    }
}