<?php
// +----------------------------------------------------------------------
// | Ht.Memorial
// +----------------------------------------------------------------------
// | Copyright (c) 2017-2017 http://www.yn123.com All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: ding <dingzhangze@163.com>
// +----------------------------------------------------------------------

namespace app\business\controller;

use think\Db;
use app\business\service\DataService;
use app\business\service\ToolsService;
/**
 * 客户管理
 * Class Title
 * @package app\admin\controller
 * @author ding <dingzhangze@163.com>
 * @date 2017/06/01
 */
class Title extends BasicBusiness
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->user = session('b_user');
        $this->uid = $this->user['create_by'];
    }

    /**
     * 指定当前数据表
     * @var string
     */
    protected $table = 'cemetery_title';

    /*
     * 列表
     */
    public function index()
    {
        // 设置页面标题
        $this->title = '回访标题管理管理';
        // 获取到所有GET参数
        $get = $this->request->get();
        // 实例Query对象
        $map = [
            'create_by' => $this->uid
        ];
        $db = Db::name($this->table)->where($map);
        // 应用搜索条件
        foreach (['title'] as $key) {
            if (isset($get[$key]) && $get[$key] !== '') {
                $db->where($key, 'like', "%{$get[$key]}%");
            }
        }
        // 实例化并显示
        parent::_list($db);
    }

    /*
     * 添加
     */
    public function add()
    {
        $this->title='添加回访标题';
        return $this->_form($this->table, 'form');
    }

    /*
    * 添加
    */
    public function edit()
    {
        $this->title='修改回访标题';
        return $this->_form($this->table, 'form');
    }

    /**
     * 删除
     */
    public function del() {
        if (DataService::update($this->table)) {
            $this->success("删除成功！", '');
        }
        $this->error("删除失败，请稍候再试！");
    }
}