<?php
// +----------------------------------------------------------------------
// | Ht.Memorial
// +----------------------------------------------------------------------
// | Copyright (c) 2017-2017 http://www.yn123.com All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: ding <dingzhangze@163.com>
// +----------------------------------------------------------------------

namespace app\business\controller;

use think\Db;
use app\business\service\DataService;
use app\business\service\ToolsService;


/**
 * 墓区设置
 * Class Cemetery
 * @package app\admin\controller
 * @author ding <dingzhangze@163.com>
 * @date 2017/06/27
 */
class Tomb extends BasicBusiness
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->user = session('b_user');
        $this->uid = $this->user['create_by'];
    }

    /**
     * 指定当前数据表
     * @var string
     */
    protected $table = 'CemeteryTomb';
    protected $RowTable = 'CemeteryTombRow';

    /**
     * 墓区管理
     */
    public function index()
    {
        // 设置页面标题
        $this->title = '墓区管理';
        // 获取到所有GET参数
        $get = $this->request->get();
        // 实例Query对象
        $map=[
            'is_deleted'=>0,
            'create_by'=>$this->uid
        ];
        $db = Db::name($this->table)->where($map);
        // 应用搜索条件
        foreach (['username', 'phone'] as $key) {
            if (isset($get[$key]) && $get[$key] !== '') {
                $db->where($key, 'like', "%{$get[$key]}%");
            }
        }
        // 分类名称
        $data = parent::_list($db, true, false);
        foreach($data['list'] as $key=>$list) {
            $data['list'][$key]['cate_name'] = Db::name('CemeteryCategory')->where('id', $list['cate_id'])->value('name');
            $data['list'][$key]['grave_name'] = Db::name('CemeteryTomb')->where('id', $list['pid'])->value('name');
        }
        // 获取分类
//        $menus = $this-> _getGrave();
//        $this->assign('menus', $menus);
        return $this->fetch('',$data);
    }

    /**
     * 分类 列表数据处理
     * @param array $data
     */
    protected function _index_data_filter(&$data)
    {

        foreach ($data as &$vo) {
            $vo['ids'] = join(',', ToolsService::getArrSubIds($data, $vo['id']));

            $exist = Db::name($this->table)->where('pid', $vo['id'])->count();
            if($exist) {
                $vo['has_child'] = true;
            }else {
                $vo['has_child'] = false;
            }
        }
        $data = ToolsService::arr2table($data);
    }
    /*
    *添加墓区
    */
    public function add()
    {
        //获取墓区
        $map=[
            'pid'=>0,
            'is_deleted'=>0,
            'create_by'=>$this->uid
        ];
        $_menus = Db::name($this->table)->where($map)->order('sort desc,id desc')->select();
//        $_menus[] = ['name' => '顶级部门', 'id' => '0', 'pid' => '-1'];
        $cate = ToolsService::arr2table($_menus);
        foreach ($cate as $key => &$menu) {
            if (substr_count($menu['path'], '-') > 3) {
                unset($cate[$key]);
                continue;
            }
            if (isset($vo['pid'])) {
                $current_path = "-{$vo['pid']}-{$vo['id']}";
                if ($vo['pid'] !== '' && (stripos("{$menu['path']}-", "{$current_path}-") !== false || $menu['path'] === $current_path)) {
                    unset($cate[$key]);
                }
            }
        }
        $this->assign('cate', $cate);
        // 获取陵园
        $menus = $this->_getGrave();
        $this->assign('menus', $menus);
        return $this->_form($this->table, 'form');
    }

    /**
     * 获取陵园 辅助方法
     * @return array
     */
    private function _getGrave() {
        $map=[
            'is_deleted'=>0,
            'create_by'=>$this->uid
        ];
        $_menus = Db::name('CemeteryCategory')->where($map)->order('sort desc,id desc')->select();
//        $_menus[] = ['name' => '顶级部门', 'id' => '0', 'pid' => '-1'];
        $menus = ToolsService::arr2table($_menus);
        foreach ($menus as $key => &$menu) {
            if (substr_count($menu['path'], '-') > 3) {
                unset($menus[$key]);
                continue;
            }
            if (isset($vo['pid'])) {
                $current_path = "-{$vo['pid']}-{$vo['id']}";
                if ($vo['pid'] !== '' && (stripos("{$menu['path']}-", "{$current_path}-") !== false || $menu['path'] === $current_path)) {
                    unset($menus[$key]);
                }
            }
        }

        return $menus;
    }

    /**
     * 编辑墓区
     */
    public function edit()
    {
        return $this->add();
    }

    /**
     * 删除墓区
     */
    public function del() {
        if (DataService::update($this->table)) {
            $this->success("删除成功！", '');
        }
        $this->error("删除失败，请稍候再试！");
    }
}
